print("-" * 50)
print("\t Welcome to the Band Name Generator")
print("-" * 50)
City = input(str("What's name of the city you grew up in?\n"))
Pet = input(str("What's youre pet's name?\n"))
print("Your band could be ",City + " " +Pet)
